name: "GET IP Iran"

on:
  push:
    branches: [ "main" ]
  schedule:
    - cron: '*/15 * * * *'

jobs:
  runscript:
    name: GetIP
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Call a Bash Script
        run:  bash get.sh >> $GITHUB_PATH
