name: "GET IP Iran"

on:
  push:
    branches: [ "main" ]
  schedule:
    - cron: '*/15 * * * *'

jobs:
  runscript:
    name: GetIP
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Call a Bash Script
        run: |
          echo "" > list.rsc
          bash get.sh
          git config --global user.email "jfararia@gmail.com"
          git config --global user.name "MrAriaNet"
          git config credential.helper store
          git add list.rsc
          git commit -am "Automatic update"
          git push
