name: "GET IP Iran"

on:
  push:
    branches: [ "main" ]
  schedule:
    - cron: '*/15 * * * *'

jobs:
  runscript:
    name: GetIP
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Call a Bash Script
        run: |
          bash get.sh > list.rsc
          git config --global user.email "47712536+MrAriaNet@users.noreply.github.com"
          git config --global user.name "MrAriaNet"
          git config credential.helper store
          git add -A
          git diff-index --quiet HEAD || git commit -m "Automatic update"
          git push -f origin main
